"""Trading signal contracts."""

from pydantic import BaseModel, Field
from typing import Optional, Dict, Any
from enum import Enum


class SignalType(str, Enum):
    """Types of trading signals."""
    ENTRY = "entry"
    EXIT = "exit"
    STOP_LOSS = "stop_loss"
    TAKE_PROFIT = "take_profit"
    REBALANCE = "rebalance"


class SignalSide(str, Enum):
    """Signal direction."""
    BUY = "buy"
    SELL = "sell"
    LONG = "long"
    SHORT = "short"


class Signal(BaseModel):
    """Trading signal generated by strategy or indicator."""
    t: int = Field(..., description="Signal timestamp in milliseconds")
    symbol: str = Field(..., description="Trading symbol")
    side: SignalSide = Field(..., description="Signal direction")
    signal_type: SignalType = Field(..., description="Type of signal")
    rule: str = Field(..., description="Rule that generated the signal")
    confidence: Optional[float] = Field(None, ge=0.0, le=1.0, description="Signal confidence 0-1")
    price: Optional[float] = Field(None, description="Suggested entry price")
    stop_loss: Optional[float] = Field(None, description="Stop loss price")
    take_profit: Optional[float] = Field(None, description="Take profit price")
    metadata: Optional[Dict[str, Any]] = Field(None, description="Additional signal data")
    
    class Config:
        use_enum_values = True

